"""init

Revision ID: 421ec5720a26
Revises: 
Create Date: 2018-06-07 00:31:20.192889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '421ec5720a26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.Column('telephone', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('ip_pools')
    op.drop_table('lianjia_data')
    op.drop_table('liepin2018s2')
    op.alter_column('liepin_2018_4', 'crawl_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('liepin_2018_4', 'job_url',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    op.alter_column('liepin_2018_4', 'salary',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.create_index(op.f('ix_liepin_2018_4_job_name'), 'liepin_2018_4', ['job_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liepin_2018_4_job_name'), table_name='liepin_2018_4')
    op.alter_column('liepin_2018_4', 'salary',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('liepin_2018_4', 'job_url',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    op.alter_column('liepin_2018_4', 'crawl_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_table('liepin2018s2',
    sa.Column('job_id', mysql.TEXT(), nullable=True),
    sa.Column('job_url', mysql.TEXT(), nullable=True),
    sa.Column('job_name', mysql.TEXT(), nullable=True),
    sa.Column('company', mysql.TEXT(), nullable=True),
    sa.Column('salary', mysql.TEXT(), nullable=True),
    sa.Column('work_location', mysql.TEXT(), nullable=True),
    sa.Column('publish_time', mysql.TEXT(), nullable=True),
    sa.Column('required_list', mysql.TEXT(), nullable=True),
    sa.Column('welfare_list', mysql.TEXT(), nullable=True),
    sa.Column('job_describe', mysql.TEXT(), nullable=True),
    sa.Column('crawl_time', mysql.TEXT(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('lianjia_data',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('main_title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('price', mysql.FLOAT(precision=10, scale=2), nullable=False),
    sa.Column('size', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('floor', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('house_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('house_orientation', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('subway', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('community', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('publish_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('seen_num', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('price_unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('crawl_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ip_pools',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('port', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('net_prot', mysql.VARCHAR(length=30), server_default=sa.text("'http'"), nullable=True),
    sa.Column('connect_time', mysql.FLOAT(precision=8, scale=4), server_default=sa.text("'0.0000'"), nullable=True),
    sa.Column('speed_time', mysql.FLOAT(precision=8, scale=4), server_default=sa.text("'0.0000'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    # ### end Alembic commands ###
